BUN_NAME = "black bun"
BUN_PRICE = 100
INGREDIENT_NAME = "hot sauce"
INGREDIENT_PRICE_1 = 50
INGREDIENT_PRICE_2 = 100
ALTERNATIVE_PRICE = 200
ALTERNATIVE_NAME = "соус с цифрами123"
INGREDIENT_TYPE = "SAUCE"